export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
export const CLEAR_CURRENT_TRACK = "CLEAR_CURRENT_TRACK";
export const NEXT_TRACK = "NEXT_TRACK";
export const PREVIOUS_TRACK = "PREVIOUS_TRACK";
export const MIX_TRACK = "MIX_TRACK";
export const PLAY = "PLAY";
export const PAUSE = "PAUSE";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const CLEAR_SEARCH_QUERY = "CLEAR_SEARCH_QUERY";

export const SET_PAGE_PLAYLIST = "SET_PAGE_PLAYLIST";
export const TOGGLE_LIKE = "TOGGLE_LIKE";

// export const SET_FILTERED_TRACKS = "SET_FILTERED_TRACKS";

export const SET_INITIAL_TRACKS = "SET_INITIAL_TRACKS";
export const SET_FILTER = "SET_FILTER";
export const SET_SEARCH = "SET_SEARCH";
